pipeline{
    agent any
    stages{
        stage('Clone repo'){
            steps{
                git branch: 'main', url: 'https://github.com/Joseclement28/Two-Tier-Flask-App.git'
            }
        }
        stage('Build image'){
            steps{
                sh 'docker build -t flask-app ./DevOps-Project-Two-Tier-Flask-App-main'
            }
        }
        stage('Deploy with docker compose'){
            steps{
                // existing container if they are running
                sh 'cd /var/lib/jenkins/workspace/flask-app/Two-Tier-Flask-App'
                sh 'docker compose down || true'
                // start app, rebuilding flask image
                sh 'docker compose up -d --build'
            }
        }
    }
}
